/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tiendapeliculas;

import Controlador.VerTabla;
import DAO.PeliculaDAO;
import Modelo.DetalleCarrito;
import Modelo.Pelicula;
import Paneles.JPanelCarrito;
import Paneles.JPanelCompra;
import Paneles.JPanelLogin;
import java.io.FileInputStream;
import java.util.ArrayList;
import javax.swing.JLabel;

/**
 *
 * @author David
 */
public class VisualAgregar extends javax.swing.JFrame {

    PeliculaDAO peliDAO;
    Pelicula pelicula;
    JPanelCompra pC;
    JPanelCarrito Pcarrito;
    String ruta = "";
    String codigo;
    float precio;
    int clic_tabla;
    JLabel lbl;
    boolean bandera = false;

    DetalleCarrito dC;
    ArrayList<DetalleCarrito> carrito;
    private FileInputStream fisfoto;
    private int longitudBytes;
    VerTabla v;

    public VisualAgregar() {
        initComponents();

        peliDAO = new PeliculaDAO();

        v = new VerTabla();

        v.visualizar_tabla(tabla);

//        JpanelMenu pm = new JpanelMenu();
//        pm.setSize(400,357);
//        pm.setLocation(0, 0);
//        
////        jPanelPrincipal.removeAll();
//        jPanelPrincipal.add(pm);
////        jPanelPrincipal.revalidate();
//        jPanelPrincipal.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPrincipal = new javax.swing.JPanel();
        btnActualizar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        btnComprar = new javax.swing.JButton();
        btnCarrito = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Perfil y foto de personas");

        jPanelPrincipal.setBackground(new java.awt.Color(204, 255, 204));
        jPanelPrincipal.setPreferredSize(new java.awt.Dimension(435, 584));

        javax.swing.GroupLayout jPanelPrincipalLayout = new javax.swing.GroupLayout(jPanelPrincipal);
        jPanelPrincipal.setLayout(jPanelPrincipalLayout);
        jPanelPrincipalLayout.setHorizontalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelPrincipalLayout.setVerticalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 628, Short.MAX_VALUE)
        );

        btnActualizar.setBackground(new java.awt.Color(204, 255, 204));
        btnActualizar.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(0, 51, 255));
        btnActualizar.setText("Actualizar y Ver Tabla");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombre", "Foto"
            }
        ));
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        btnComprar.setText("Comprar");
        btnComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarActionPerformed(evt);
            }
        });

        btnCarrito.setText("Carrito");
        btnCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarritoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnComprar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(btnCarrito, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 617, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnActualizar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAgregar)
                            .addComponent(btnComprar)
                            .addComponent(btnCarrito))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        if (!bandera) {
            v.visualizar_tabla(tabla);
        } else {
            carrito = Pcarrito.RetornaCarrito();
            v.visualizar_tabla2(tabla, carrito);
        }

    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        bandera = false;
        JPanelLogin pL = new JPanelLogin(tabla);
        pL.setSize(440, 628);
        pL.setLocation(0, 0);

        jPanelPrincipal.removeAll();
        jPanelPrincipal.add(pL);
        jPanelPrincipal.revalidate();
        jPanelPrincipal.repaint();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
        clic_tabla = tabla.rowAtPoint(evt.getPoint());

        codigo = "" + tabla.getValueAt(clic_tabla, 0);
        String titulo = "" + tabla.getValueAt(clic_tabla, 1);

//        txtCodigo.setText(String.valueOf(codigo));
//        txtNombre.setText(titulo);
//        txtPrecio.setText(String.valueOf(precio));
        if (!bandera) {
            try {
                lbl = (JLabel) tabla.getValueAt(clic_tabla, 2);
                pC.VerElemento(lbl, codigo, titulo);

            } catch (Exception ex) {
                System.out.print("Error al ingresar");
            }        // TODO add your handling code here:
        } else {
            int cantidad = Integer.parseInt("" + tabla.getValueAt(clic_tabla, 2));
            float precio = Float.parseFloat("" + tabla.getValueAt(clic_tabla, 3));
            float subtotal = Float.parseFloat("" + tabla.getValueAt(clic_tabla, 4));
            Pcarrito.VerElemento(codigo, titulo, cantidad, precio, subtotal, clic_tabla);
        }
    }//GEN-LAST:event_tablaMouseClicked

    private void btnComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarActionPerformed
        bandera = false;
        v.visualizar_tabla(tabla);

        pC = new JPanelCompra(carrito);
        pC.setSize(440, 628);
        pC.setLocation(0, 0);

        jPanelPrincipal.removeAll();
        jPanelPrincipal.add(pC);
        jPanelPrincipal.revalidate();
        jPanelPrincipal.repaint();
    }//GEN-LAST:event_btnComprarActionPerformed

    private void btnCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarritoActionPerformed
        bandera = true;
        if (carrito != null) {
            carrito = pC.RetornaCarrito();
        } else {
            carrito = new ArrayList<DetalleCarrito>();  
        }
        
        v.visualizar_tabla2(tabla, carrito);
        Pcarrito = new JPanelCarrito(carrito);
        Pcarrito.setSize(440, 628);
        Pcarrito.setLocation(0, 0);

        jPanelPrincipal.removeAll();
        jPanelPrincipal.add(Pcarrito);
        jPanelPrincipal.revalidate();
        jPanelPrincipal.repaint();

    }//GEN-LAST:event_btnCarritoActionPerformed

    public void acumAreglo(ArrayList<DetalleCarrito> carrito) {
        carrito = carrito;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisualAgregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisualAgregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisualAgregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisualAgregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VisualAgregar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCarrito;
    private javax.swing.JButton btnComprar;
    public static javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
